    const lunchesNearYou = 'Lunches Near You';
    const titleLine = 'Discussion about design and technology ecosystem';
    const getDirection = 'Get Directions';
    const location = 'Panaro\'s Restaurant';
    const today = 'Today';
    const pm = '2PM';
    const connectOverPizza = 'Connect Over Pizza';
    const twoSpotLeft = '2 spots left';
    const lunchTitle = 'Lunch with Matt Demon';
    const loc = 'Onley Avenue';
    export {lunchesNearYou, titleLine, getDirection, location, today, pm, connectOverPizza, twoSpotLeft,lunchTitle, loc};